apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-web
  labels:
    app: flask-web
    environment: staging
spec:
  replicas: 2  # Moderate replicas for staging
  selector:
    matchLabels:
      app: flask-web
  template:
    metadata:
      labels:
        app: flask-web
        environment: staging
    spec:
      containers:
      - name: web
        image: ghcr.io/rajeshfintech/flask-web:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "staging"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet: { path: /healthz, port: 8080 }
          initialDelaySeconds: 3
          periodSeconds: 8
        livenessProbe:
          httpGet: { path: /healthz, port: 8080 }
          initialDelaySeconds: 8
          periodSeconds: 12
