apiVersion: v1
kind: Namespace
metadata:
  name: github-runner
---
apiVersion: v1
kind: Secret
metadata:
  name: github-runner-token
  namespace: github-runner
type: Opaque
stringData:
  token: "YOUR_GITHUB_TOKEN_HERE"  # Replace with your GitHub token
  url: "https://github.com/rajeshkarunakaran/me-test"  # Replace with your repo URL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      serviceAccountName: github-runner
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: REPO_URL
          valueFrom:
            secretKeyRef:
              name: github-runner-token
              key: url
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner-token
              key: token
        - name: RUNNER_NAME
          value: "podman-kind-runner-low"
        - name: RUNNER_WORKDIR
          value: "/tmp/runner/work"
        - name: RUNNER_GROUP
          value: "default"
        - name: LABELS
          value: "podman-kind,kubectl,kubernetes,low-resource"
        - name: EPHEMERAL
          value: "true"
        - name: KUBECONFIG
          value: "/home/runner/.kube/config"
        volumeMounts:
        - name: kubeconfig
          mountPath: /home/runner/.kube
          readOnly: true
        - name: work
          mountPath: /tmp/runner/work
        # Reduced resource requirements
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"      # Reduced from 500m
          limits:
            memory: "1Gi"    # Reduced from 2Gi
            cpu: "500m"      # Reduced from 1500m
      volumes:
      - name: kubeconfig
        secret:
          secretName: kubeconfig-secret
      - name: work
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner
  namespace: github-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-runner
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: github-runner
subjects:
- kind: ServiceAccount
  name: github-runner
  namespace: github-runner
