apiVersion: v1
kind: Namespace
metadata:
  name: github-runner
---
apiVersion: v1
kind: Secret
metadata:
  name: github-runner-token
  namespace: github-runner
type: Opaque
stringData:
  token: "YOUR_GITHUB_TOKEN_HERE"
  url: "https://github.com/rajeshfintech/me-test"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      serviceAccountName: github-runner
      containers:
      - name: runner
        image: sumologic/github-actions-runner:latest
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner-token
              key: token
        - name: GITHUB_REPOSITORY
          value: "rajeshfintech/me-test"
        - name: RUNNER_NAME
          value: "podman-kind-stable"
        - name: RUNNER_LABELS
          value: "podman-kind,kubernetes,stable"
        - name: RUNNER_GROUP
          value: "default"
        volumeMounts:
        - name: kubeconfig
          mountPath: /home/runner/.kube
          readOnly: true
        - name: work
          mountPath: /tmp/runner/work
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: kubeconfig
        secret:
          secretName: kubeconfig-secret
      - name: work
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-runner
  namespace: github-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-runner
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: github-runner
subjects:
- kind: ServiceAccount
  name: github-runner
  namespace: github-runner
