apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: flask-web-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: rajeshkarunakaran/me-test  # Replace with your repo
      labels:
        - kind-cluster
        - docker
      dockerdWithinRunnerContainer: true
      containers:
      - name: runner
        image: summerwind/actions-runner:latest
        env:
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: work
          mountPath: /runner/_work
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: work
        emptyDir: {}
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: flask-web-runner-autoscaler
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: flask-web-runner
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - rajeshkarunakaran/me-test  # Replace with your repo
