apiVersion: v1
kind: Service
metadata:
  name: flask-web
  labels:
    app: flask-web
spec:
  type: ClusterIP
  selector:
    app: flask-web
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
