name: CI • Build with Self-Hosted Runner

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build_and_test:
    runs-on: [self-hosted, linux]  # Use your self-hosted runner
    steps:
    - name: Checkout code
      run: |
        # Assuming git is pre-installed on self-hosted runner
        git clone https://github.com/${{ github.repository }}.git .
        git checkout ${{ github.sha }}

    - name: Install Python dependencies
      run: |
        # Assuming Python is pre-installed
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt

    - name: Run tests
      run: pytest -q

    - name: Build and push Docker image
      run: |
        # Build image
        docker build -t flask-web:${{ github.sha }} .
        
        # Login and push
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
        OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
        IMAGE="ghcr.io/${OWNER}/flask-web"
        
        # Tag and push
        docker tag flask-web:${{ github.sha }} ${IMAGE}:sha-${{ github.sha }}
        docker push ${IMAGE}:sha-${{ github.sha }}
        
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          docker tag flask-web:${{ github.sha }} ${IMAGE}:latest
          docker push ${IMAGE}:latest
        fi
