name: Trigger Local Deployment

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Deployment message'
        required: false
        default: 'Triggered from GitHub Actions'

jobs:
  trigger_deploy:
    runs-on: [self-hosted, podman-kind]
    
    steps:
    - name: Trigger local deployment
      run: |
        echo "🚀 Triggering local deployment..."
        echo "Message: ${{ github.event.inputs.message || 'Auto-triggered deployment' }}"
        
        # Create a signal file that can be picked up by a local script
        echo "DEPLOY_TRIGGER=true" > /tmp/github-deploy-trigger
        echo "COMMIT_SHA=${{ github.sha }}" >> /tmp/github-deploy-trigger
        echo "REPOSITORY=${{ github.repository }}" >> /tmp/github-deploy-trigger
        echo "TIMESTAMP=$(date)" >> /tmp/github-deploy-trigger
        
        echo "✅ Deployment trigger created at /tmp/github-deploy-trigger"
        echo "📋 Trigger file contents:"
        cat /tmp/github-deploy-trigger
